### ISSUE TITLE
Cannot find module 'loglevel'

### ISSUE THREAD

**Issue by AlexGustafsson** [plasticrake/hs100-api#12]
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'loglevel'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/homebridge/node_modules/hs100-api/lib/logger.js:5:13)
    at new Client (/homebridge/node_modules/hs100-api/lib/client.js:20:35)
    at new Hs100Platform (/homebridge/node_modules/homebridge-hs100/lib/platform.js:36:19)
    at Server._loadPlatforms (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/cli.js:40:10)
```

The package loglevel is not referenced as a dependency in package.json, only a dev-dependency.

**Comment by plasticrake** [comment]
Fixed. thanks!
