### ISSUE TITLE
Error thrown in client.startDiscovery()

### ISSUE THREAD

**Issue by andrewmacheret** [plasticrake/hs100-api#8]
When running the following code (copied from the readme with a few lines commented out):

```js
const Hs100Api = require('hs100-api');

const client = new Hs100Api.Client();
//const plug = client.getPlug({host: '10.0.1.2'});
//plug.getInfo().then(console.log);
//plug.setPowerState(true);

// Look for plugs, log to console, and turn them on
client.startDiscovery().on('plug-new', (plug) => {
  plug.getInfo().then(console.log);
  //plug.setPowerState(true);
});
```

The following error is thrown as a result of calling startDiscovery:

```
/usr/src/app/node_modules/hs100-api/lib/plug.js:61
    this.supportsConsumption = (sysInfo.feature.includes('ENE'));
                                               ^

TypeError: Cannot read property 'includes' of undefined
    at Plug.set sysInfo [as sysInfo] (/usr/src/app/node_modules/hs100-api/lib/plug.js:61:48)
    at Client.<anonymous> (/usr/src/app/node_modules/hs100-api/lib/client.js:75:22)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)
```

It looks like the sysInfo being passed into the setSysInfo block doesnt have a feature property, but I haven't had a chance to dig deeper. 

This is with hs100-api 0.4.0: `"hs100-api": "^0.4.0",`

**Comment by andrewmacheret** [comment]
I added debugging and saw this in the console output:
```
DEBUG - {"emeter":{"err_code":-2001,"err_msg":"Module not support"},"system":{"get_sysinfo":{"sw_ver":"1.4.3 Build 170504 Rel.144921","hw_ver":"1.0","model":"LB100(US)","description":"Smart Wi-Fi LED Bulb with Dimmable Light","alias":"Alfa Romeo","mic_type":"IOT.SMARTBULB","dev_state":"normal","mic_mac":"50C7BF310610","deviceId":"{DEVICEID}","oemId":"{OEMID}","hwId":"{HWID}","is_factory":false,"disco_ver":"1.0","ctrl_protocols":{"name":"Linkie","version":"1.0"},"light_state":{"on_off":0,"dft_on_state":{"mode":"normal","hue":0,"saturation":0,"color_temp":2700,"brightness":100}},"is_dimmable":1,"is_color":0,"is_variable_color_temp":0,"preferred_state":[{"index":0,"hue":0,"saturation":0,"color_temp":2700,"brightness":100},{"index":1,"hue":0,"saturation":0,"color_temp":2700,"brightness":75},{"index":2,"hue":0,"saturation":0,"color_temp":2700,"brightness":25},{"index":3,"hue":0,"saturation":0,"color_temp":2700,"brightness":1}],"rssi":-47,"active_mode":"none","heapsize":302452,"err_code":0}}} from 192.168.0.163
```

**Comment by robertsundstrom** [comment]
It is probably a firmware issue. Sometimes the data that is being received is incomplete. I don’t know if it’s isolated to UDP.

I had to catch and wait for a retry when I wrote code in C#.

**Comment by plasticrake** [comment]
The `feature` issue should be fixed now. I never had any bulbs to test with, but I have a simulator now. It's allowed me to really improve support!
